### ISSUE TITLE
Replace the GraphGenerationFailedException by an exception from the Core Framework

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-yaml2-plugin#8]
### Task Description

**As developer** of the YAML II plugin for jQA,
**I would like** to replace the `GraphGenerationFailedException` by a better exception, provided by the Core Framework of jQA,
**so that** we have more consistent design.

### Additional Resources 

* jQAssistant/jqa-core-framework#53

### Definition of Done for the Implementers
- [ ] Unittests have been written
- [ ] Integration tests have been written
- [ ] Test coverage is the same or even better then before
